# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RoadTripPlanner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RoadTripPlanner
  pod 'FBSDKCoreKit', '4.27.1'
  pod 'FBSDKLoginKit', '4.27.1'
  pod 'Parse'
  
  target 'RoadTripPlannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoadTripPlannerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
